React redux components
mullenlucas/react-bookstore pull request #3
Opened 2022-09-28 18:05 UTC by mullenlucas

## Implemented features:

- Added the `react-redux` and `uuid` packages
- Modified the initial state in books.js to a sample array of books. Instanciated useSelector() to consume this initial state array to display the books
- Used redux Provider to update information on the App.js components
- Generated unique IDs for each book via the uuid package
- Implemented functionality to add new books by dispatching the action of addBook()
- Implemented functionality to remove books by dispatching the action of removeBook()
- Implemented functionality to check book status by dispatching the action of statusChecker()

2022-09-28 18:30 UTC, Omar-Muhamad requested changes
# Changes Required ♻️
### Hi @mullenlucas,

Nice job, you are almost there.

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- Gitflow is used correctly. ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- [ ] Please check the inline comments below.

## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-09-28 18:30 UTC, Omar-Muhamad commented on src/components/BooksGen.js
> +          </button>
- [ ] Clicking on the remove button suppose to dispatch the remove action and remove the book from the page and this is not happining. So please fix that.

![chrome-capture-2022-8-28](https://user-images.githubusercontent.com/68796232/192860106-97b50dc6-fc5b-4f48-94c6-4e1605909e84.gif)

2022-09-28 18:30 UTC, Omar-Muhamad commented on src/display/Categories.js
> +      </button>
- [ ] Clicking on the `check status` button suppose to show `under construction` the text data you get from dispatching `statusChecker` action. So please fix that.

![chrome-capture-2022-8-28 (1)](https://user-images.githubusercontent.com/68796232/192860727-3aa13947-436d-4ce3-993b-b6dc15d8f120.gif)

2022-09-29 15:47 UTC, ShahierNashaat approved these changes
Hi @mullenlucas, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 💯 

- Correct use of GitFlow ✔️
- Descriptive commit messages ✔️
- Professional looking pull request ✔️
- Your readme looks professional ✔️
- Your code is clean and well documented ✔️

# Approved :ok_hand: :ok_hand: :ok_hand:

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-29 16:25 UTC, merged